spring:
  application:
    name: car-service
  datasource:
    url: jdbc:postgresql://localhost:5432/carmanagement_car
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8082

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


car:
  scoring:
    weights:
      usage: 0.4
      recency: 0.3
      price: 0.3
    price:
      thresholds:
        low: 30     # Excellent score
        medium: 60  # Good score
        high: 100   # Average score

logging:
  level:
    com.carmanagement.car: DEBUG
    org.hibernate.SQL: DEBUG

jwt:
  secret: "mySuperSecretKeyForJWTTokenGenerationInCarManagementSystem2024"